name: 'pr-stats'
author: 'Andrzej Wódkiewicz'
description: 'Calculate simple PR statistics'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  token:
    description: 'Your workflow GITHUB_TOKEN secret'
    required: true
branding:
  icon: git-pull-request
  color: purple