name: "simple-pr-stats"
author: "Andrzej Wódkiewicz"
description: "Calculate simple PR statistics"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  token:
    description: "Your workflow GITHUB_TOKEN secret"
    required: true
  days_back:
    description: "Number of days defining the earliest PR creation date to be included in the calculations"
    required: false
    default: 30
  labels_to_ignore:
    description: "PR with these labels will be ignored. Values delimited with commas"
    required: false
  include_drafts:
    desription: "If set to true, draft PRs will be included in the calculations"
    required: false
    default: false
branding:
  icon: git-pull-request
  color: purple
