on: pull_request

jobs:
  x1_job:
    runs-on: ubuntu-latest
    name: Run action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: x1 step
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days_back: 10
          labels_to_ignore: good first issue, invalid
